# Tarefa 1
FROM python:3

COPY carguru.py /app/carguru.py

WORKDIR /app

CMD ["python", "carguru.py"]


# NO TERMINAL
# Construir a imagem
# docker build -t imagem_carguru .

# Iniciando o container
# docker run --name imagem_carguru

# Executar o container
# docker run imagem_carguru


# Tarefa 2 

# Sim, é possível reutilizar containers. Se você tiver containers parados, pode reiniciá-los usando o comando docker start. 

# Reiniciando um container parado:
# docker start imagem_carguru
